package xkfx.tools.tuna.model;

import org.hibernate.validator.constraints.Range;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.id
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.front
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    @NotBlank(message = "front不能为空")
    private String front;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.back
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    @NotBlank(message = "back不能为空")
    private String back;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.target_id
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    @NotNull(message = "targetId不能为空")
    @Range(min = 1000L, message = "targetId不规范")
    private Long targetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.id
     *
     * @return the value of card.id
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.id
     *
     * @param id the value for card.id
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.front
     *
     * @return the value of card.front
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public String getFront() {
        return front;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.front
     *
     * @param front the value for card.front
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public void setFront(String front) {
        this.front = front == null ? null : front.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.back
     *
     * @return the value of card.back
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public String getBack() {
        return back;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.back
     *
     * @param back the value for card.back
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public void setBack(String back) {
        this.back = back == null ? null : back.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.target_id
     *
     * @return the value of card.target_id
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.target_id
     *
     * @param targetId the value for card.target_id
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    @Override
    public String toString() {
        return "Card{" +
                "id=" + id +
                ", front='" + front + '\'' +
                ", back='" + back + '\'' +
                ", targetId=" + targetId +
                '}';
    }
}