package xkfx.tools.tuna.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import xkfx.tools.tuna.model.Card;

import java.util.List;

public interface CardMapper {

    List<Card> listCard(@Param("targetId") Long targetId,
                        @Param("offset") Integer offset,
                        @Param("limit") Integer limit);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    Card selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Card record);
}