package xkfx.tools.tuna.dao;

import xkfx.tools.tuna.model.Target;

import java.util.List;

public interface TargetMapper {

    List<Target> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int insert(Target record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int insertSelective(Target record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    Target selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Target record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Mar 09 19:07:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Target record);
}